name: Build and Deploy Document
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Build document
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        build-command: "sphinx-build -b html . _build"

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: _build
