name: Test Document Build
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Test document Build
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        build-command: "sphinx-build -b html . _build"
